version: "3.9"

services:
    apache2:
        container_name: apache2
        image: apache2image
        build:
            context: .
            dockerfile: docker/apache2/DockerFile
        volumes:
            - ./:/var/www
        ports:
            - "80:82"
            - "443:443"