version: "3.9"

services:
  nginx:
    container_name: nginx_balancer
    image: nginx:latest
    ports:
      - "81:81"
    volumes:
      - ./docker/nginx/hosts:/etc/nginx/conf.d
    links:
      - apache1
      - apache2
    depends_on:
      - apache1
      - apache2

  apache1:
    container_name: apache1_balancer
    build:
      context: .
      dockerfile: docker/DockerFile
    volumes:
      - ./:/var/www
      - ./docker/apache1/conf/apache2.conf:/etc/apache2/apache2.conf
  apache2:
    container_name: apache2_balancer
    build:
      context: .
      dockerfile: docker/DockerFile
    volumes:
      - ./:/var/www
      - ./docker/apache2/conf/apache2.conf:/etc/apache2/apache2.conf
